---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: rkm
    role: outpost
  name: rkm-outpost
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rkm-outpost
subjects:
- kind: ServiceAccount
  name: rkm-outpost
  namespace: rkm-outpost