---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: rkm
    role: outpost
  name: rkm-outpost
rules:
- apiGroups:
  - ""
  resources:
  - componentstatuses
  - nodes
  - endpoints
  verbs:
  - get
  - list
  - watch