---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: rkm
    role: outpost
  name: rkm-outpost
spec:
  schedule: {{ .Values.schedule.outpost | quote }}
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: rkm
            role: outpost
        spec:
          securityContext:
            runAsUser: 10000
            runAsGroup: 10000
            fsGroup: 10000
          containers:
          - name: rkm-outpost
            image: {{ .Values.repository.outpost }}:latest
            imagePullPolicy: IfNotPresent
            securityContext:
             allowPrivilegeEscalation: false
             #readOnlyRootFilesystem: true
             capabilities:
               drop:
                - ALL
            env:
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: rkm-config
                    key: TZ
              - name: CLUSTER_NAME
                valueFrom:
                  configMapKeyRef:
                    name: rkm-config
                    key: CLUSTER_NAME
              - name: INFLUXDB_URL
                valueFrom:
                  configMapKeyRef:
                    name: rkm-config
                    key: INFLUXDB_URL
              - name: INFLUXDB_PORT
                valueFrom:
                  configMapKeyRef:
                    name: rkm-config
                    key: INFLUXDB_PORT
              - name: INFLUXDB_NAME
                valueFrom:
                  configMapKeyRef:
                    name: rkm-config
                    key: INFLUXDB_NAME
              {{- if .Values.rkmMissionControl.authEnabled }}
              - name: AUTH_ENABLED
                value: "true"
              - name: INFLUXDB_USER
                valueFrom:
                  secretKeyRef:
                    name: rkm-secrets
                    key: INFLUXDB_USER
              - name: INFLUXDB_PW
                valueFrom:
                  secretKeyRef:
                    name: rkm-secrets
                    key: INFLUXDB_PW
              {{- end }}
              - name: VERBOSE
                value: {{ .Values.verbose | quote }}
              {{- if .Values.httpProxy }}
              - name: HTTP_PROXY
                value: {{ .Values.httpProxy }}
              {{- end }}
              {{- if .Values.httpsProxy }}
              - name: HTTPS_PROXY
                value: {{ .Values.httpsProxy }}
              {{- end }}
              {{- if .Values.customCA }}
              - name: CURL_CA_BUNDLE
                value: /etc/ssl/custom-ca
              {{- end }}
            resources:
              requests:
                memory: "45Mi"
                cpu: "15m"
              limits:
                memory: "80Mi"
                cpu: "1000m"
          {{- if .Values.customCA }}
            volumeMounts:
            - mountPath: /etc/ssl/custom-ca
              name: custom-ca
          volumes:
          - name: rancher-data
            configMap:
              name: custom-ca
          {{- end }}
          restartPolicy: OnFailure
          serviceAccountName: rkm-outpost
