---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-rkm
spec:
  podSelector:
    matchLabels:
      app: rkm
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: {{ .Values.clusterInformation.kubeAPIServerPort }}
    - protocol: TCP
      port: {{ .Values.rkmMissionControl.influxDBPort }}