# Default values for RKM.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Docker Image information
repository:
  outpost: quay.io/onzack/rkm-outpost
  outpostOperator: quay.io/onzack/rkm-outpost-operator

# Kubernetes cluster information for RKM to collect the correct metrics
clusterInformation:
  clusterName: cluster-1
  kubeAPIServerPort: 6443
  tz: Europe/Zurich

# RKM-Outpost schedules
schedule:
  outpost: "* * * * *"
  outpostOperator: "* 6 * * 2"

# InfluxDB configuration for RKM Mission Control
rkmMissionControl:
  authEnabled: true
  # NOTE: If authEnabled=true, the chart expects InfluxDB with authentication and you need to create a Kubernetes secret with that information
  # -> kubectl create secret generic rkm-secrets --from-literal=INFLUXDB_USER=<user> --from-literal=INFLUXDB_PW=<password> -n <rkm-namespace>
  influxDBURL: http://influxdb.example.com
  influxDBPort: 80
  influxDBName: rkm

# Debug mode prints the metrics to /dev/stdout
debug: false
