---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: rkm
    role: outpost-operator
  name: rkm-outpost-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rkm-outpost-operator
subjects:
- kind: ServiceAccount
  name: rkm-outpost-operator
  namespace: rkm-outpost